#!/usr/bin/php -q
<?php

/**
 *  @file
 *  A script to enforce ownership of drupal and wordpress webroots.
 */

/**
 *  This script is designed to enforce ownership settings on a wordpress or
 *  drupal webroot. Permissions are defined n the 3 dimensional array called
 *  $desired_settings. All files are checked first to see if any settings need
 *  to be changed; if so, changes are attempted. Both successes and failures
 *  are logged (log file is ./setown.log). Failures also generate error
 *  messages in STDOUT.
 *
 *  Written by Chris McDermott, AppliedTrust, chris@appliedtrust.com
 *    v1.2 11/04/2011
 *
 *  @param platform (-p)
 *    Specify the software platform to check. Acceptable values are
 *    "wordpress", "drupal6", and "drupal7".
 *  @param target (-t)
 *    Specify the directory where the software platform is installed. This is
 *    the base directory used for all file interactions.
 *  @param owner (-o)
 *    Specify a default owner for files in the webroot (perhaps the primary
 *    developer). This is an optional parameter - if it is omitted this
 *    defaults to "root".
 *  @param group (-g)
 *    Similar to the owner parameter - this is the default group that should be
 *    applied to webroot files. This is an optional parameter - if it is
 *    omitted this defaults to "root".
 *  @param webuser (-w) 
 *    Optional. Sets the user account in use by the web server (for things lik
 *    e file upload directories). Defaults to "apache".
 *  @param default_fileperm (-f)
 *    Optional. Sets the default permissions to use for files. Defaults to 644.
 *  @param default_dirperm (-i)
 *    Optional. Sets the default permissions to use for directories. Defaults
 *    to 755.
 *  @param debug (-d)
 *    Optionally enable extra debugging statements.
 *
 *  @return
 *    Returns true if no errors were encountered, false otherwise.
 */
putenv('TZ=America/Denver');
$debug = 0;
$logfile = './setown.log';

// Start parsing arguments
$options = getopt("p:t:o:g:w:f:i:dh");
if (isset($options['h'])) { usage(); };
if (!isset($options['p'])) { 
  log_this("error", "-p option is required."); 
  usage(); 
}
if (!isset($options["t"])) { 
  log_this("error", "-t option is required."); 
  usage(); 
}
if (isset($options["o"])) { 
  if (!user_exists($options["o"])) {
    log_this("error", "User: " . $options["o"] . " does not exist, please specify a valid user account.");
    exit(2);
  }
  $owner = $options["o"]; 
}

//  If no owner is provided, default to "root".
else {
  $owner = "root"; 
}

if (isset($options["g"])) { 
  if (!group_exists($options["g"])) {
    log_this("error", "Group: " . $options["g"] . " does not exist, please specify a valid group.");
    exit(2);
  }
  $group = $options["g"]; 
}

//  If no group is provided, default to "root".
else {
  $group = "root";
}

if (isset($options["w"])) { 
  $webuser = $options["w"]; 
}
//  If no webuser is provided, default to "apache".
else {
  $webuser = "apache";
}

// If no file or directory permissions are specified, default to 644 and 755.
if (isset($options["f"])) {
  $default_fileperm = $options["f"];
}
else {
  $default_fileperm = 644;
}
if (isset($options['i'])) {
  $default_dirperm = $options['i'];
}
else {
  $default_dirperm = 755;
}

if (($options["p"] != "wordpress") && ($options["p"] != "drupal6") && ($options["p"] != "drupal7")) { 
  log_this("error", "$options[p] is not a supported platform."); 
  usage(); 
}

if (isset($options["d"])) { $debug = 1; }
$platform = $options["p"];
$target = $options["t"];

//  If debug was toggled, log all arguments
if ($debug) {
  foreach($options as $key=>$value) {
    log_this("debug", "option $key: $value");
  }
}

//  If the target directory doesn't exist, bail out with an error.
if (!file_exists($target)) {
  log_this("error", "$target does not exist.");
  exit(2);
}

//  If the target directory doesn't look like an installation of the specified
//  platform, bail out with an error.
elseif (!validate_target($platform, $target)) {
  log_this("error", "$target does not look like a valid $platform webroot.");
  exit(2);
}

log_this("info", "Starting job.");

// If the $target has a trailing slash, get rid of it.
if (preg_match("/(.*)\/$/", $target, $matches)) {
  $target = $matches[1];
}

$successes = array();
$errors = array();

/**
 *  @array $desired_perms
 *    A 3 dimensional array of ownership settings for each platform.
 *    -platform: An array of supported platforms:
 *      -file: An array of settings for the named file:
 *        -owner: A string specifying the desired owner.
 *        -group: A string specifying the desired group.
 *        -perm: An int specifying the desired permission.
 * 
 *  In summary, this script applies default ownership and permission settings
 *  except for the files/folders explictly listed in this array, which are
 *  applied as described.
 */
$desired_perms = array(
  "wordpress" => array( 
    "wp-admin" => array(
      "owner" => "root",
      "group" => "root",
      "perm" => 755,
    ),
    "wp-content" => array(
  	  "owner" => $owner,
  	  "group" => $group,
          "perm" => 755,
    ),
    "wp-includes" => array(
      "owner" => "root",
      "group" => "root",
      "perm" => 755,
    ),
    "wp-content/uploads" => array(
     "owner" => $webuser,
     "group" => $group,
      "perm" => 775,
    ),
    ".htaccess" => array(
      "owner" => "root",
      "group" => "root",
      "perm" => 644,
    ),
  ),
  "drupal6" => array(
    "sites/default/settings.php" => array(
      "owner" => "root",
      "group" => "root",
      "perm" => 644,
    ),
    ".htaccess" => array(
      "owner" => "root",
      "group" => "root",
      "perm" => 644,
    ),
    "sites/all/modules" => array(
      "owner" => $owner,
      "group" => $group,
      "perm" => 775,
    ),
    "sites/all/themes" => array(
      "owner" => $owner,
      "group" => $group,
      "perm" => 775,
    ),
    "sites/all/libraries" => array(
      "owner" => $owner,
      "group" => $group,
      "perm" => 775,
    ),
    "sites/default/files" => array(
      "owner" => $webuser,
      "group" => $group,
      "perm" => 775,
    ),
  ),
  "drupal7" => array(
    "sites/default/settings.php" => array(
      "owner" => "root",
      "group" => "root",
      "perm" => 644,
    ),
    ".htaccess" => array(
      "owner" => "root",
      "group" => "root",
      "perm" => 644,
    ),
    "sites/all/modules" => array(
      "owner" => $owner,
      "group" => $group,
      "perm" => 775,
    ),
    "sites/all/themes" => array(
      "owner" => $owner,
      "group" => $group,
      "perm" => 775,
    ),
    "sites/all/libraries" => array(
      "owner" => $owner,
      "group" => $group,
      "perm" => 775,
    ),
    "sites/default/files" => array(
      "owner" => $webuser,
      "group" => $group,
      "perm" => 775,
    ),
  ),
);


/**
 *  This is where stuff actually starts happening!
 *
 *  First apply ownership settings to the root directory. Because
 *  apply_settings works recursively, this sets default owner, group
 *  and permssions on everything that's not explicitly defined in the
 *  desired_perms array.
 */
apply_settings($target, $owner, $group, $default_fileperm, $default_dirperm);

//  Next, iterate through each file in the array of settings for the provided
//  platform and apply the settings to it.
foreach ($desired_perms[$platform] as $file=>$setting) {
  if (!file_exists("$target/$file")) { 
    log_this("debug", "$target/$file does not exist, skipping.");
    continue;
  };
  log_this("debug", "Applying settings to $target/$file.");
  apply_settings("$target/$file", $setting["owner"], $setting["group"], $setting["perm"], $setting["perm"]);
  //  I used $setting["perm"] twice because each file specified in $desired_perms has only one permission defined,
  //  but apply_settings requires 2 because it operates on both files and directories, and needs to know in some
  //  cases (when it's acting recursively) what to do for both.
}

//  Check for errors, return true or false, depending.
log_this("info", "Job complete. " . count($successes) . " files successfully modified and " . count($errors) . " errors logged.");
if (count($errors) == 0) {
  return true;
}
else {
  return false;
}

/**
 *  And that's it. The script is done!
 */




/**
 *  Prints usage information and argument requirements.
 */
function usage () {
  echo "Usage: setown -p <wordpress|drupal6|drupal7> -t <targetdir> [-o owner] [-g group] [-d]\n";
  echo "  -p platform         drupal6|drupal7|wordpress         required\n";
  echo "  -t target           /var/www/html/wordpress           required\n";
  echo "  -o owner            username                          optional, defaults to root\n";
  echo "  -g group            groupname                         optional, defaults to root\n";
  echo "  -w webuser          username(apache,www-user)         optional, defaults to apache\n";
  echo "  -f fileperm         permission(644)                   optional, defaults to 644\n";
  echo "  -i dirperm          permission(755)                   optional, defaults to 755\n";
  echo "  -d                                                    optional, toggles debug\n\n";
  exit (2);
}

/**
 *  Logs a message.
 *  
 *  Supports various message types, including debug, error, and info. Debug 
 *  messages are printing to STDOUT, while error messages are printed to STDOUT 
 *  and the log file, and info messages are only printed to the log file.
 *
 *  @param string $type
 *    "debug" and "error" are handled specially, everything else ("info", for
 *    instance) is just written to the log file.
 *
 *  @param string $message
 *    The message to log. Newline is appended to the end automatically, so
 *    there's no need to include it.
 */
function log_this ($type, $message) {
  global $logfile, $debug;
  $handle = fopen($logfile, "a");
  $timestamp = date("Y-m-d H:i") . "\t";
  if ($type == "error") {
    echo "ERROR: " . $message . "\n";
    fwrite($handle, $timestamp . $message . "\n");
  }
  elseif (($type == "debug") && ($debug == 1)) {
    echo "DEBUG: " . $message . "\n";
    //fwrite($handle, $timestamp . $message . "\n");
  }
  else {
    fwrite($handle, $timestamp . $message . "\n");
  }
  fclose($handle);
}

/**
 *  Checks the target location provided to ensure that it looks like a valid 
 *  $platform webroot.
 *
 *  @param string $platform
 *    Web platform to check for - "wordpress" or "drupal6" or whatever.
 *  @param string $target
 *    The target location to check.
 *
 *  @return
 *    True if the webroot is confirmed to be a $platform install, otherwise
 *    false.
 */
function validate_target ($platform, $target) {
  if ($platform == "wordpress") {
    if(!file_exists("$target/wp-config.php") || !file_exists("$target/wp-admin/") || !file_exists("$target/wp-content/")) {
      return false;
    }
    else { return true; }
  }
  else if (preg_match("/drupal/", $platform)) {
    if(!file_exists("$target/sites/default/settings.php") || !file_exists("$target/includes/") || !file_exists("$target/modules/node/")) {
      return false;
    }
    else { return true; }
  }
  else {
    log_this("error", "Could not validate target directory, are you sure that $platform is a valid platform?");
    return false;
  }
}

/**
 *  Sets owner and group of specified file.
 *
 *  Owner and group are checked first, and if the settings are already correct,
 *  no action is taken. If they are not correct, the owner and/or group is
 *  changed appropriately. If the file is a directory, a find command
 *  identifies any files or subdirectories that also require changes, and the
 *  function is called recursively on each of those.
 *
 *  All changes, whether successful or not, are logged.
 *
 *  @param $file
 *    Full path to file.
 *  @param $owner
 *    User name of desired owner.
 *  @param $group
 *    Name of desired group.
 *  @param $fileperm
 *    Permission to use for files.
 *  @param $dirperm
 *    Permission to use for directories.
 *
 *  @return
 *    True if the settings were applied successfully, otherwise false.
 */
function apply_settings ($file, $owner, $group, $fileperm, $dirperm) {
  global $debug, $errors, $successes, $desired_perms, $platform, $target, $default_fileperm, $default_dirperm;
  if (in_array($file, $errors) || in_array($file, $successes)) { 
    log_this("debug", "$file was already attempted.");
    return false;
  }
  //  Parse for just the filename
  if (preg_match("@$target/(.+)$@", $file, $matches)) {
    //  If that doesn't exist in $desired_perms, then set the $fileperm and $dirperm to default
    if (!array_key_exists($matches[1], $desired_perms[$platform])) {
      $fileperm = $default_fileperm;
      $dirperm = $default_dirperm;
    }
  }
  $current_owner = user_name(fileowner($file));
  $current_group = group_name(filegroup($file));
  $current_perm = substr(decoct(fileperms($file)), 3);
  switch (filetype($file)) {
    case "file": 
      if ($current_owner != $owner) {
        change_owner($file, $owner);
      }
      if ($current_group != $group) {
        change_group($file, $group);
      }
      if ($current_perm != $fileperm) {
        change_permission($file, $fileperm);
      }
      break;
    case "dir":
      if ($current_owner != $owner) {
        change_owner($file, $owner);
      }
      if ($current_group != $group) {
        change_group($file, $group);
      }
      if ($current_perm != $dirperm) {
        change_permission($file, $dirperm);
      }

      //  Find files that do not have the right owner, group, or permissions.
      //  We'll go through and fix them all recursively in a second.
      exec("find $file -not -user $owner", $owner_files);
      exec("find $file -not -group $group", $group_files);
      exec("find $file -type f -not -perm $fileperm", $perm_files);
      exec("find $file -type d -not -perm $dirperm", $perm_dirs);

      if (count($owner_files) > 0) {
        foreach ($owner_files as $bad_file) {
          //  If one of the results is the file we're already working on, then skip it.
          if ($bad_file == $file) {
            continue;
          }
          //  Parse for just the filename
          if (preg_match("@$target/(.+)$@", $bad_file, $matches)) {
            //  If that exists in desired_perms then skip it, since we'll come back
            //  to it later.
            if (array_key_exists($matches[1], $desired_perms[$platform])) {
              log_this("debug", "$bad_file is explicitly defined later, skipping.");
              continue;
            }
          }
          apply_settings($bad_file, $owner, $group, $fileperm, $dirperm);
        }
      }
      if (count($group_files) > 0) {
        foreach ($group_files as $bad_file) {
          //  Parse for just the filename
          if (preg_match("@$target/(.+)$@", $bad_file, $matches)) {
            //  If that exists in desired_perms then skip it, since we'll come back
            //  to it later.
            if (array_key_exists($matches[1], $desired_perms[$platform])) {
              log_this("debug", "$bad_file is explicitly defined later, skipping.");
              continue;
            }
          }
          apply_settings($bad_file, $owner, $group, $fileperm, $dirperm);
        }
      }
      if (count($perm_files) > 0) {
        foreach ($perm_files as $bad_file) {
          //  If one of the results is the file we're already working on, then skip it.
          if ($bad_file == $file) {
            continue;
          }
          //  Parse for just the filename
          if (preg_match("@$target/(.+)$@", $bad_file, $matches)) {
            //  If that exists in desired_perms then skip it, since we'll come back
            //  to it later.
            if (array_key_exists($matches[1], $desired_perms[$platform])) {
              log_this("debug", "$bad_file is explicitly defined later, skipping.");
              continue;
            }
          }
          apply_settings($bad_file, $owner, $group, $fileperm, $dirperm);
        }
      }
      if (count($perm_dirs) > 0) {
        foreach ($perm_dirs as $bad_file) {
          //  Parse for just the filename
          if (preg_match("@$target/(.+)$@", $bad_file, $matches)) {
            //  If that exists in desired_perms then skip it, since we'll come back
            //  to it later.
            if (array_key_exists($matches[1], $desired_perms[$platform])) {
              log_this("debug", "$bad_file is explicitly defined later, skipping.");
              continue;
            }
          }
          apply_settings($bad_file, $owner, $group, $fileperm, $dirperm);
        }
      }
      break;
  }
  //  Check to see if changes were successful.
  $new_current_owner = user_name(fileowner($file));
  $new_current_group = group_name(filegroup($file));
  $new_current_perm = substr(decoct(fileperms($file)), 3);
  if (($new_current_owner == $owner) && ($new_current_group == $group)) {
    if (((filetype($file) == 'file') && ($new_current_perm == $fileperm)) || ((filetype($file) == 'dir') && ($new_current_perm == $dirperm))) {
      //  If the owner, group, and permissions all look right, then return true.
      return true;
    }
    //  The permissions are wrong - return false.
    return false;
  }
  else {
    //  Either the owner or the group is wrong - return false.
    return false;
  }
}

/** 
 *  Changes the owner of specified file.
 */
function change_owner ($file, $owner) {
  global $successes, $errors;
  $current_owner = user_name(fileowner($file));
  exec("/bin/chown $owner $file 2>&1", $output, $return);
  if (!$return) {
    log_this("info", "Changed owner of $file from $current_owner to $owner.");
    array_push($successes, $file);
    return true;
  }
  else {
    log_this("error", "Failed to change owner of $file from $current_owner to $owner.");
    array_push($errors, $file);
    return false;
  }
}

/** 
 *  Changes the group of specified file.
 */
function change_group ($file, $group) {
  global $successes, $errors;
  $current_group = group_name(filegroup($file));
  exec("/bin/chgrp $group $file 2>&1", $output, $return);
  if (!$return) {
    log_this("info", "Changed group of $file from $current_group to $group.");
    $successes++;
    return true;
  }
  else {
    log_this("error", "Failed to change group of $file from $current_group to $group.");
    $errors++;
    return false;
  }
}

/**
 *  Changes the permission of the specified file.
 */
function change_permission ($file, $perm) {
  global $successes, $errors;
  $current_perm = substr(decoct(fileperms($file)), 2);
  if ($current_perm == $perm) {
    return true;
  }
  exec("/bin/chmod $perm $file", $output, $return);
  if (!$return) {
    log_this("info", "Changed permission of $file from $current_perm to $perm.");
    $successes++;
    return true;
  }
  else {
    log_this("error", "Failed to change permission of $file from $current_perm to $perm.");
    $errors++;
    return false;
  }
}

/** 
 *  Checks if the specified group exists.
 */
function group_exists ($group) {
  exec("/bin/grep $group: /etc/group", $output, $return);
  if ($return != 0) {
    return false;
  }
  return true;
}

/**
 *  Checks if the specified user exists.
 */
function user_exists ($user) {
  exec("/bin/grep $user: /etc/passwd", $output, $return);
  if ($return != 0) {
    return false;
  }
  return true;
}

/**
 *  Convert uid to user name.
 */
function user_name ($uid) {
  exec("grep $uid /etc/passwd | cut -d':' -f1", $output, $return);
  if ($return != 0) {
    return false;
  }
  return $output[0];
}

/**
 *  Convert gid to group name.
 */
function group_name ($gid) {
  exec("grep $gid /etc/group | cut -d':' -f1", $output, $return);
  if ($return != 0) {
    return false;
  }
  return $output[0];
}

?>
